### ISSUE TITLE
init_db example

### ISSUE THREAD

**Issue by DiEVeXx** [tobias-piotr/alchemist#3]
Hi! I would like to know how to create a file to initialize the database with some ingredients when starting the application, since the repositories depend on the dependency injection through fastapi I can't find a way to do it.

Thank you very much for your time

**Comment by ttyobiwan** [comment]
Hi @DiEVeXx, thank you for taking a look! Repositories are indeed used with the FastAPI dependency injection, but in the end it is a code that can be used in any script. So, you can just create a repository object like in the dependency:

```python
repo = repository.DatabaseRepository(models.Ingredient, session)
```

And use it as you like. The most important part that is handled by the dependency injection is the SQLAlchemy session. In your script, you can either get it manually, like I did in the migration script, or you can use the same `get_db_session` utility, but instead of relying on FastAPI, you can just use it like a regular generator.

Hope that helps you move in a better direction :smile:
